frontier_explorer:
  ros__parameters:
    use_naive: false
    viewpoint_depth: 1.0
    use_action_client_node: true
    entropy_radius: 2.4
    robot_radius: 0.35
    use_entropy_calc: false
    use_sampling: true
    sampling_threshold: 250

nav_to_pose:
  ros__parameters:
    pose_frame: "map"